const { Client } = require('pg');
const fs = require('fs');
const path = require('path');
require('dotenv').config();

const client = new Client({
  connectionString: process.env.DATABASE_URL
});

async function run() {
  try {
    await client.connect();
    
    // Read the schema file generated by node scripts
    const schemaSql = fs.readFileSync(path.join(__dirname, '../old_schema.sql'), 'utf8');
    
    console.log("Executing old_schema.sql...");
    await client.query(schemaSql);
    console.log("Schema creation successful!");
    
    // Let's also verify tables now
    const res = await client.query(`
      SELECT table_name 
      FROM information_schema.tables 
      WHERE table_schema = 'public'
    `);
    console.log("Tables in database:", res.rows.map(r => r.table_name));
    
  } catch (err) {
    console.error("Error executing schema:", err);
  } finally {
    await client.end();
  }
}

run();
